#!/usr/bin/python
###
# Weather Display Pressure
#
# This is a plugin for munin which uses the weather display plugin to display
# various pressure settings.
#
# Link this as wdpressure_www.example.com
#
# Where www.example.com is the url of the weather display output, the tool
# currently expects to find clientraw.txt at http://www.example.com/clientraw.txt
# 
# @author Marcus Povey <marcus@marcus-povey.co.uk>
# @copyright Marcus Povey 2013
# @link http://www.marcus-povey.co.uk
# 
# Copyright (c) 2013 Marcus Povey
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of
# this software and associated documentation files (the "Software"), to deal in
# the Software without restriction, including without limitation the rights to
# use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of
# the Software, and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
# FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
# COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER
# IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
# CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
###

import sys
import os

def main(argv):
	
	PATH = '../wd-parse.py'
	command = argv[0].split('_')

	url = command[1] + '/clientraw.txt'
	format = '"current.value {{6}}"'

	if len(argv) > 1 and argv[1] == 'config':
		print 'graph_args --base 1000 -l 0' 
		print 'graph_scale no'
		print 'graph_title Weather Display Pressure'
		print 'graph_vlabel Pressure hPa'
                print 'graph_category weather'
		print 'current.label Pressure'
		sys.exit()

	os.system(PATH + ' -o ' + format + ' -u ' + 'http://'+url)
	
if __name__ == "__main__":
    sys.exit(main(sys.argv))
